#!/bin/sh
/usr/lib/agora/.env/bin/pip uninstall Agora-Stoa-Client
/usr/lib/agora/.env/bin/pip uninstall Agora-Fragments
/usr/lib/agora/.env/bin/pip install git+https://github.com/fserena/agora-stoa-client.git@develop
/usr/lib/agora/.env/bin/pip install git+https://github.com/fserena/agora-fragments.git@develop

/usr/lib/agora/.env/bin/fragments &
