#!/bin/sh
if [ -z "$AGORA_FRAGMENTS_VERSION" ]; then    
    /usr/lib/agora/.env/bin/pip install --upgrade Agora-Fragments
else
	/usr/lib/agora/.env/bin/pip install --upgrade Agora-Fragments==$AGORA_FRAGMENTS_VERSION
fi

/usr/lib/agora/.env/bin/fragments &